### ISSUE TITLE
Segmentation function not working

### ISSUE THREAD

**Issue by Tommy-Ngx** [lannguyen0910/food-recognition#20]
Thank @kaylode and @lannguyen0910! you guys did a well-done project. I have tried to run the app notebook and found that the segmentation function is not working basically. the detection is working fine. Could you please check it out? 
I see you using Unet++ from segmentation from [segmentation_models.pytorch](https://github.com/qubvel/segmentation_models.pytorch). Could you please share with me a training notebook? I find it hard to make the right setup and data preparation. I would like to understand how to implement it correctly. You can share with me via my email at tommyfederation@gmail.com. Thank you so much!

**Comment by lannguyen0910** [comment]
Hi @Tommy-Ngx, thanks for your question! The segmentation function is working normally, you can check out the image at ```static/assets/segmentations/.../masks``` path, it doesn't show up in the webapp because i set the wrong path, i will fix it soon. For the segmentation model, may i let @kaylode make it clear for you for more in-depth info.

**Comment by kaylode** [comment]
Hi @Tommy-Ngx, you can refer to this [https://colab.research.google.com/drive/1AoQPbXJifRdrAlVRF5NEFSAoftgQ9z1_?usp=sharing](link), there are some code snippets for preparing the custom dataset. Basically, you need to write your own class to load the image and mask. Then, modify the configuration to use that class. Please look into that notebook, and feel free to ask if there is any question

**Comment by Tommy-Ngx** [comment]
@kaylode @lannguyen0910 Thank you so much for your friendly and supportive reply!
