### ISSUE TITLE
Upload Food

### ISSUE THREAD

**Issue by ctu1121** [lannguyen0910/food-recognition#24]
Hi I upload food photo, press Detect and see Internal Server Error message. Please advise how could I use it. Thanks.

![messageImage_1677752240016](https://user-images.githubusercontent.com/1059430/222401441-c691a1b9-e271-41d7-ab62-9f14ca502b18.jpg)
![messageImage_1677752196191](https://user-images.githubusercontent.com/1059430/222401461-3cd19455-1e84-4b3f-b4e2-baaa743cda3f.jpg)

**Comment by lannguyen0910** [comment]
Hi @ctu1121, I think it has a problem with the weight in the ```gdown``` cell, the weights cannot be downloaded so it triggers that error. I will look into the problem in the future, if you have any solution to download the weights, please let me know. Thank you!
