### ISSUE TITLE
ERROR: No matching distribution found for opencv-python-headless==4.2.0.32

### ISSUE THREAD

**Issue by lalolita** [lannguyen0910/food-recognition#25]
I'm getting the following error after cloning the project and running `pip install -e .`. Any idea what might be causing this? Thanks!

> ERROR: Could not find a version that satisfies the requirement opencv-python-headless==4.2.0.32 (from food-recognition) (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72)
ERROR: No matching distribution found for opencv-python-headless==4.2.0.32

System Information:
Apple M1
macOS 13.1
python 3.10.6
pip 23.0.1

**Comment by lannguyen0910** [comment]
Dear @lalolita, it seems like you had a problem with installing ```opencv-python-headless==4.2.0.32``` package. Maybe you should try to install another package like: ```4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72```
If doesn't work either, please comment to let me know, I will look for a solution. Thank you!

**Comment by lalolita** [comment]
Thanks @lannguyen0910, apparently the last version 4.7.0.72 works great!

**Comment by lannguyen0910** [comment]
Thank you! I will update the requirements based on your solution.
