### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

### ISSUE THREAD

**Issue by alexhmyang** [lannguyen0910/food-recognition#26]
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by lannguyen0910** [comment]
Hi @alexhmyang , to load the weight you need to have GPU on your computer and more specifically, installed CUDA on it. If you don't have GPU then you should use my code on google colab. Sincere!

**Comment by alexhmyang** [comment]
thanks!  where is colab code ? I havent fount it

**Comment by lannguyen0910** [comment]
Here is the [link](https://drive.google.com/file/d/1CGEtC65kvoZ-4tcqzeknGrbERvb0beuU/view?usp=sharing), you can try it, but I saw that it has some issue with downloading the weights. So I will try to solve it asap!

**Comment by jaykay9999** [comment]
i had a similar issue, chatgpt helped a bit but what worked for me is changing cuda:0 with cpy in the device parameter in the 3 .yaml files in in the config folder

**Comment by lannguyen0910** [comment]
Yes, I forgot that I have included a device parameter in the config files. But I don't know if it works anymore in this version. Feel free to play with those configs and contact me if any issue happens. Thanks!
