### ISSUE TITLE
Inference Colab notebook ngrok agent version too old

### ISSUE THREAD

**Issue by coolteemf** [lannguyen0910/food-recognition#32]
Hi,
Thank you for putting together this app !
I tried to run the inference notebook on [Colab,](https://colab.research.google.com/drive/1X06Y-HSPeHbEWtsXpyal8R1PliiVvpJq?usp=sharing) but I got an error with the ngrok version: 
```
Your ngrok-agent version "2.3.41" is too old. The minimum supported agent version for your account is "3.2.0". Please update to a newer version with `ngrok update`, by downloading from https://ngrok.com/download, or by updating your SDK version. Paid accounts are currently excluded from minimum agent version requirements. To begin handling traffic immediately without updating your agent, upgrade to a paid plan: https://dashboard.ngrok.com/billing/subscription.

ERR_NGROK_121
```
However, when I run ngrok update in the notebook, it says it's up to date:
`!/ngrok update`
`No update available, this is the latest version.`
Output of `!/ngrok --version`:
`ngrok version 2.3.41`

I'm not familiar with ngrok, so I don't quite know how to solve the issue right now.

**Comment by Instincts03** [comment]
Did you found the solution, i am facing the same issue

**Comment by coolteemf** [comment]
> Did you found the solution, i am facing the same issue

Sadly, no.

**Comment by lannguyen0910** [comment]
Hi @coolteemf and @Instincts03 , sorry for the late response! I have fixed the following error in the newest commit. I hope this will help you in some way. Thank you!
